### ISSUE TITLE
Help with combining datasets from multiple years where some years have a comment field and other years not.

### ISSUE THREAD

**Issue by degagnon2018** [TobieSurette/gulf.manage#8]
Je sais pas comment dealer avec ça pour combiner les multiples années. Avec un if else statement peut être? Donnes moi des tips. C'est pour la demande à Geneviève Côté. J'ai sauvé le code que j'ai dans gulf.manage/requests/SCS.

**Comment by TobieSurette** [comment]
Je les fonctions 'read' du gulf package ont été modifiées pour permettre des tables de données avec différentes variables d'une année à l'autre ou d'un ensemble de données à l'autre.
